version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      production-deps:
        dependency-type: production
        update-types:
          - patch
      dev-deps:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - ci
    commit-message:
      prefix: chore
      include: scope
